Nsaktaganov resolve issue 110
KaymeKaydex/go-vshard-router pull request #111
Opened 2024-12-12 18:49 UTC by nurzhan-saktaganov

What has been done? Why? What problem is being solved?

I didn't forget about (remove if it is not applicable):

- [ ] Changelog (see [documentation](https://keepachangelog.com/en/1.0.0/) for changelog format)

Related issues:

2024-12-12 22:49 UTC, nurzhan-saktaganov commented
Benchmarks:

```
n.saktaganov@n-saktaganov tnt % make bench
go test -bench=. -benchmem
goos: darwin
goarch: arm64
pkg: github.com/KaymeKaydex/go-vshard-router/tests/tnt
cpu: Apple M3 Pro
BenchmarkCallSimpleInsert_GO_RouterCall-12         10719            109068 ns/op            1937 B/op         37 allocs/op
BenchmarkCallSimpleInsert_GO_Call-12                9900            109099 ns/op            1833 B/op         33 allocs/op
BenchmarkCallSimpleInsert_Lua-12                    7352            164535 ns/op            1228 B/op         20 allocs/op
BenchmarkCallSimpleSelect_GO_RouterCall-12         13227             88042 ns/op            2687 B/op         52 allocs/op
BenchmarkCallSimpleSelect_GO_Call-12               13088             87874 ns/op            2131 B/op         41 allocs/op
BenchmarkCallSimpleSelect_Lua-12                    8695            137136 ns/op            1305 B/op         22 allocs/op
PASS
ok      github.com/KaymeKaydex/go-vshard-router/tests/tnt       21.921s
```

2024-12-13 14:51 UTC, nurzhan-saktaganov commented on api.go
> +func (r *Router) RouterCallImpl(ctx context.Context,
+get rid of RouterCallImpl in `func (r *Router) Do(req *CallRequest, userMode pool.Mode) *CallResponse {`

2024-12-13 14:51 UTC, nurzhan-saktaganov commented on api.go
> +const (
Add comments for public/exported stuff

2024-12-18 19:36 UTC, KaymeKaydex commented
looks very cool, as discussed we will fix the standard implementation of RouterCallImpl, although it is not optimal, since it decodes empty interfaces. Standard Call will allow to fix this. And also the next pr we will fix the sugar resolution and make it optimal

2024-12-18 21:55 UTC, nurzhan-saktaganov commented on api.go
> +func (r *Router) RouterCallImpl(ctx context.Context,
#120

2024-12-19 09:04 UTC, KaymeKaydex requested changes

2024-12-19 09:04 UTC, KaymeKaydex commented on api.go
> +// Use Call, Call[RO, RW, RE, BRO, BRE] methods instead.
```suggestion
// Use Call, Call with RO, RW, RE, BRO, BRE methods instead.
```
cause call is non generic

2024-12-19 09:04 UTC, KaymeKaydex commented on replicaset.go
> +// Deprecated: RouterCallImpl is deprecated,
```suggestion
```
method comment mismatch

2024-12-19 09:19 UTC, nurzhan-saktaganov commented on CHANGELOG.md
> +* New methods 'Router.Call[XYZ]' to replace the deprecated one 'RouterCallImpl'.
fixed

2024-12-19 09:19 UTC, nurzhan-saktaganov commented on api.go
> +// Use Call, Call[RO, RW, RE, BRO, BRE] methods instead.
fixed

2024-12-19 09:19 UTC, nurzhan-saktaganov commented on replicaset.go
> +// Deprecated: RouterCallImpl is deprecated,
fixed

2024-12-19 09:22 UTC, nurzhan-saktaganov commented on api.go
> +	callTimeoutDefault = 500 * time.Millisecond
Since this value is intended to be used only for internal purposes, I guess we should leave it non-public.

2024-12-19 14:14 UTC, KaymeKaydex approved these changes

2024-12-19 14:14 UTC, merged