fixes for #78
KaymeKaydex/go-vshard-router pull request #81
Opened 2024-09-23 13:46 UTC by nurzhan-saktaganov

- simplify test/tnt/{Makefile,router.lua)
- indent fix for test/tnt/storage.lua

2024-09-23 14:56 UTC, KaymeKaydex approved these changes

2024-09-25 12:23 UTC, KaymeKaydex requested changes

2024-09-25 12:23 UTC, KaymeKaydex commented on CHANGELOG.md
> +* simplify test/tnt/{Makefile,router.lua)
need to write it upside

2024-09-25 20:40 UTC, nurzhan-saktaganov commented on CHANGELOG.md
> +* simplify test/tnt/{Makefile,router.lua)
Fixed

2024-09-26 09:20 UTC, KaymeKaydex approved these changes

2024-09-26 09:20 UTC, merged