partially resolve issue #77
KaymeKaydex/go-vshard-router pull request #95
Opened 2024-09-26 21:03 UTC by nurzhan-saktaganov

* RouterCallImpl: retry on BucketResolve error
* RouterCallImpl: do not retry on vshard error "TRANSFER_IS_IN_PROGRESS"
* RouterCallImpl: remove misleading RetryOnCall

2024-09-27 06:51 UTC, KaymeKaydex commented on api.go
> +			case "TRANSFER_IS_IN_PROGRESS":
please, when making such changes, attach similar logic from lua vshard

2024-09-28 07:54 UTC, KaymeKaydex requested changes
looks correct instead CHANGELOG.
pls fix this little problem and lets merge it

2024-09-28 07:54 UTC, KaymeKaydex commented on CHANGELOG.md
> +* RouterCallImpl: retry on BucketResolve error
```suggestion
* RouterCallImpl: retry on BucketResolve error.
```

2024-09-28 07:54 UTC, KaymeKaydex commented on CHANGELOG.md
> +* RouterCallImpl: do not retry on vshard error "TRANSFER_IS_IN_PROGRESS"
```suggestion
* RouterCallImpl: do not retry on vshard error "TRANSFER_IS_IN_PROGRESS".
```

2024-09-28 07:54 UTC, KaymeKaydex commented on CHANGELOG.md
> +* RouterCallImpl: remove misleading RetryOnCall
```suggestion
* RouterCallImpl: remove misleading RetryOnCall.
```

2024-10-01 10:41 UTC, nurzhan-saktaganov commented
> looks correct exclude CHANGELOG. pls fix this little problem and lets merge it

Fixed

2024-10-01 11:12 UTC, KaymeKaydex approved these changes

2024-10-01 11:12 UTC, merged